name: Donation Proposal
description: Propose to donate a preexisting project to the OpenTelemetry organization
title: "[Donation Proposal]: "
labels: ["donation"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the OpenTelemetry project! 👋🎉
        Please review the [Donation Guidelines](https://github.com/open-telemetry/community/blob/main/guides/contributor/donations.md) before submitting this form.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the project you want to donate.
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Benefits to the OpenTelemetry community
      description: How may this project benefit the OpenTelemetry community?
    validations:
      required: true
  - type: textarea
    id: reasons
    attributes:
      label: Reasons for donation
      description: |
        Please explain why an OpenTelemetry donation is necessary to realize these benefits.
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Repository
      description: Where is the project currently hosted?
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: Existing usage
      description: Summary of existing usage of donated project.
    validations:
      required: true
  - type: textarea
    id: maintenance
    attributes:
      label: Maintenance
      description: Please explain how the project is going to be maintained if the donation is accepted.
    validations:
      required: true
  - type: textarea
    id: license
    attributes:
      label: Licenses
      description: How is the project's code currently licensed?
    validations:
      required: true
  - type: textarea
    id: trademarks
    attributes:
      label: Trademarks
      description: List of trademarks
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other notes
      description: Other things that the OpenTelemetry Technical or Governance committees should know.
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
